### ISSUE TITLE
PropertiesParser always parses as ConfigString

### ISSUE THREAD

**Issue by javaerb** [typesafehub/config#133]
PropertiesParser always interprets system properties as String, unlike file-based config where types such as Number or Boolean are derived based on the value. This causes an inconsistency where, say, a property in a .conf file is normally parsed as a Boolean, but when overridden using -D on the java commandline, now is received as a String, even if a valid Boolean value is specified in that override..

**Comment by vjkoskela** [comment]
I am experiencing a similar issue. I completely agree that the parser is behaving as documented; however, for values specified in the file some type discovery does appear to occur. For the hocon file:

```
foo=1
bar="1"
```

This leads to rendering a JSON file:

```
{
  "foo":1,
  "bar:"1"
}
```

(more on how and why below)

So in this case the parser does seem to recognize that foo is an integer while bar is a string. I'm not sure if this was the intention of the parser and renderer, but it certainly seem to be the effect. Unfortunately, when overriding an integer with a property file or environment variable the type of the overridden value is forced back into a string. For example:

```
> export FOO_OVERRIDE=2
```

```
foo=1
foo=${?FOO_OVERRIDE}
bar="1"
```

This leads to JSON:

```
{
  "foo":"2",
  "bar:"1"
}
```

I completely agree that the environment variable and property file cannot describe the type, but one could attempt to infer the type from the existing value. For example, if the value already specified is an integer and the environment variable can be interpreted as an integer then it is. Of course, this only works if there is something to infer from in the Hocon file. However, at least in our case this covers the use case completely (base hocon file w/ overrides from the environment).

Here is my Hocon to JSON render code:

```
    public JsonObject parse(final String configuration) {
        final Config config = ConfigFactory.parseString(configuration);
        final String hoconAsJson = config.resolve().root().render(ConfigRenderOptions.concise());
        return new JsonObject(hoconAsJson);
    }
```

The reason I am doing this is to use Hocon configuration with a system that accepts only JSON. In the code above I accept the raw configuration String, parse it as Hocon, render it as JSON and finally parse it as Json. Except for this issue (hopefully there are no others) this has been a great way to replace our JSON configuration with Hocon configuration without rewriting third-party libraries/frameworks.

If there is a way for me to intercept the resolve or render process to perform the type conversion based on the default value and environment value please let me know. Or if this functionality does not exist but could be added, some pointers on where to start would be greatly appreciated.

Sincerely,
Ville Koskela

**Comment by broilogabriel** [comment]
I'm facing the same issue @vjkoskela listed above, is there any recommended solution for something like:
```
foo=1
foo=${?FOO_OVERRIDE}
bar="1"
```

**Comment by havocp** [comment]
The way it usually works is that the getters on `Config` perform type conversions, so for example `config.getInt("foo")` would convert a string-that-is-an-integer to an actual integer.
There's no schema system, so type conversion happens at the getter.

**Comment by broilogabriel** [comment]
Hi @havocp, do you have any idea why I would get this exception?

```
port = 6379
port = ${?SOME_PORT}
---
val port = settings.getInt("port")
---
com.typesafe.config.ConfigException$WrongType: env variables: port has type STRING rather than NUMBER
```

**Comment by leozilla** [comment]
I actually have the same problem as @broilogabriel 
If I substitute a config value with a value from an environment variable it always uses STRING as the type, as environment variables are defined as Strings.

This exactly becomes problematic if you want your config values to be of another type, eg an Integer for the Port number.

I guess the only solution is to use String for the config field, right?

**Comment by havocp** [comment]
I would expect that if port is a string which parses as a number, and you call getInt, then it would be parsed into an int. If that isn't happening then I'm surprised by it; could be something like unexpected whitespace or non-digit characters, possibly, or maybe the getInt isn't actually the line that throws, I'm not sure.

**Comment by leozilla** [comment]
Sorry @havocp, you are right, it was a mistake on my side while setting the env variable

**Comment by tinchou** [comment]
I've hit this issue too. It's impossible to check `ConfigValueType` in this case, and I can't call `getLong` when using `Config#entrySet`, which makes things cumbersome.

I ended up calling `getLong(entry.getKey())` and catching `ConfigException.WrongType`.

**Comment by noahlz** [comment]
I am getting this error:

`system properties: <key> has type STRING rather than BOOLEAN`

Seems reasonable that the code getting this error should be able to coerce the STRING to a BOOLEAN.  `Boolean.valueOf(String)` anyone?

**Comment by havocp** [comment]
Can you provide a test case or more detail? I think that should work but could misremember

**Comment by noahlz** [comment]
I am working on a simple reproduction but having trouble. Here is the stacktrace from our application:
version is 1.4.0
```
com.typesafe.config.ConfigException$WrongType: system properties: <key> has type STRING rather than BOOLEAN
  at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:163)
  at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
  at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
  at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
  at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
  at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
  at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:218)
  ...
```

**Comment by havocp** [comment]
I believe this code should run: https://github.com/lightbend/config/blob/f92a4ee2f672c8254d87b27831d0903d3d0d6cc2/config/src/main/java/com/typesafe/config/impl/DefaultTransformer.java#L42-L49

called from here: https://github.com/lightbend/config/blob/f92a4ee2f672c8254d87b27831d0903d3d0d6cc2/config/src/main/java/com/typesafe/config/impl/SimpleConfig.java#L159-L160

but if it doesn't work that way I'm not sure what is happening.

**Comment by noahlz** [comment]
I swear this happened for me earlier (see stack trace) but I cannot reproduce it and it went away in my project as well.

https://github.com/noahlz/lightbend-config-test

Not sure what to make of this. If someone wants to fork my project to reproduce this issue, by all means have at it!
