### ISSUE TITLE
errors when extendedDebugInfo switch is enabled, even for valid configs

### ISSUE THREAD

**Issue by lJoublanc** [typesafehub/config#176]
in v1.2.1, enabling the system flag

-Dsun.io.serialization.extendedDebugInfo=true

which is intended to make Java serialization verbose, raises the following error instead

~~~~
Caused by: com.typesafe.config.ConfigException$BugOrBroken: com.typesafe.config.impl.SerializedConfigValue should not exist outside of serialization
  at com.typesafe.config.impl.SerializedConfigValue.shouldNotBeUsed(SerializedConfigValue.java:471)
  at com.typesafe.config.impl.SerializedConfigValue.unwrapped(SerializedConfigValue.java:482)
  at com.typesafe.config.impl.AbstractConfigValue.render(AbstractConfigValue.java:325)
  at com.typesafe.config.impl.AbstractConfigValue.render(AbstractConfigValue.java:321)
  at com.typesafe.config.impl.AbstractConfigValue.toString(AbstractConfigValue.java:282)
  at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1418)
  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
  at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
  at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
  at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
  at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
  at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
  at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
  at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
~~~~

It looks like this is because the flag enables printing out the object name and then writing a string representation, outside the context of the `Config` class...

This debug flag is useful in the case when you have a lot of nested objects, and are trying to figure out which one is causing serialization to fail. However, this bug throws up this error even for valid instance of Config, hence making the flag unusable.

**Comment by ScrapCodes** [comment]
Any update on this ? is this fixed

**Comment by havocp** [comment]
No, but planning a sprint soon to roll up a lot of smaller fixes into a release.

**Comment by ScrapCodes** [comment]
Thanks for the update, @havocp.
