### ISSUE TITLE
`include file()` is not relative to the file doing the including

### ISSUE THREAD

**Issue by Soren025** [typesafehub/config#202]
When writing plugins for Bukkit, the plugin's data folder is located at "plugins/[plugin name]".

In order to make use of "include file()" I must enter in that entire path before hand such that it looks like this "foo = { include file("plugins/[plugin name]/bar.conf }. I want the include to implicitly assume the "plugins/<plugin name/" to keep my config files clean.

I have have a feeling It can be done by implementing "ConfigIncluder" but I have not figured out how to do this.

**Comment by havocp** [comment]
I added PR #277 which tests and documents the current behavior. Right now only the "heuristic" includes (without file()) do the "look adjacent" trick. I think we should probably change this, though it would technically be a semantic ABI break. But the code needs to be reshuffled a bit to make this change, it isn't 100% trivial. In the meantime the situation is "works as designed, but design decision was kinda bad."

**Comment by DanieleSassoli** [comment]
any updates on this?

**Comment by havocp** [comment]
No idea offhand. I guess you are trying a thing like `include "../foo.conf"` ? I don't think there's a test case for that in the test suite, I don't know whether it works, I think it should work in the same cases that `include "./foo.conf"` does, but perhaps it does not if nobody has ever tried it until now.

**Comment by wuservices** [comment]
After a bunch of attempts, I'm fairly certain that `include "../foo.conf` does not work. Unfortunately, due to #122, this makes it hard to add a magic default that would load an `environment.conf` from certain places relative to the project or in the user's homedir. I'll probably load `environment.conf` using `-Dconfig.file`, then add `include "application"` to that instead.

**Comment by javadba** [comment]
Referencing a local path is not working as follows:

For the following configuratoin:

```
sqls = {
  scoring = {
    scoringSummarySql = """select MatchMethod, F1, rsF1, Precision, Recall, TP, FP, FN from scoring"""
 }
```

This works if the above snippet is directly inside the calling file - but gives the following error if using the following include directive:

include "matching-sqls.conf"


```
String: 117: Could not resolve substitution to a value: ${sqls.scoring.scoringSummarySql}
com.typesafe.config.ConfigException$UnresolvedSubstitution: String: 117: Could not resolve substitution to a value: ${sqls.scoring.scoringSummarySql}

```

I am fine to do any kind of relative or local path for includes - but is anything working presently?

**Comment by anilkumarmyla** [comment]
> I'm having problems including a configuration from a file located in a parent directory, but I don't have problems when including from the same directory or children directory... any idea?

I've found traversing the whole resource path easier to include a file from parent directory

Let's say you have `a/b/c/d.conf` doing an `include "../../e.conf"` to actually include `a/e.conf`, it doesn't work. You need to do `include "/a/e.conf"`

**Comment by yunjiangster** [comment]
This is a major bug that my project cannot live with, since we'd like all our include paths to be relative within a git repository. Here is an easy way to reproduce the bug:

1. clone https://github.com/vlad2/hocon-config-printer and install 
2. create the following directory structure and files
`cat subdir/a.conf`
> {
>     a: b
> }

`cat subdir/b.conf`
> {
>   include file("a.conf")
>   a: ${a}
> }

3. `hocon-config-printer subdir/b.conf -resolve`
> Exception in thread "main" com.typesafe.config.ConfigException$UnresolvedSubstitution: subdir/b.conf: 3: Could not resolve substitution to a value: ${a} was part of a cycle of substitutions involving ${a}, ${a}
> 	at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:104)
> 	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:183)
> 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:146)
> 	at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:380)
> 	at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:313)
> 	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:399)
> 	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:183)
> 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:146)
> 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:235)
> 	at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:79)
> 	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:69)
> 	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:64)
> 	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:42)
> 	at ro.vdin.configprinter.ConfigPrinter.printConfig(ConfigPrinter.java:15)
> 	at ro.vdin.configprinter.ConfigPrinterMain.main(ConfigPrinterMain.java:24)
> Caused by: com.typesafe.config.impl.AbstractConfigValue$NotPossibleToResolve: was not possible to resolve
> 	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:180)
> 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:146)
> 	at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:88)
> 	... 14 more

**Comment by adampauls** [comment]
Is there even a reasonable workaround? I think bare `include "foo/bar.conf"` is not platform independent because of the "/"?
