### ISSUE TITLE
ConfigException still not quite serialisable?

### ISSUE THREAD

**Issue by lloydmeta** [typesafehub/config#288]
/grumble Github is being DDoS'ed...5th time trying

As requested in #42 [here](https://github.com/typesafehub/config/issues/42#issuecomment-86807116)

This is the exception that I'm seeing.

```
java.io.NotSerializableException: com.typesafe.config.impl.SimpleConfigOrigin
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.scalatest.tools.SocketReporter.apply(SocketReporter.scala:31)
	at org.scalatest.DispatchReporter$Propagator$$anonfun$run$1.apply(DispatchReporter.scala:240)
	at org.scalatest.DispatchReporter$Propagator$$anonfun$run$1.apply(DispatchReporter.scala:239)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:239)
	at java.lang.Thread.run(Thread.java:745)`
```

A test that reproduces this in Scala (sorry don't know enough Java):

```scala
import org.scalatest.{ Matchers, FunSpec }
import play.api.Configuration

class ConfigProblemSpec extends FunSpec with Matchers {

  def doWithConfig(config: Configuration): Unit = {
    config.getStringList("item")
  }

  describe("#boom") {

    it("will blow") {
      val config = Configuration.from(
        Map(
          "item" -> "uhoh, it's gonna blow"
        )
      )
      doWithConfig(config)
    }
  }

}
```

**Comment by havocp** [comment]
I tried to break this but it isn't breaking: https://github.com/typesafehub/config/commit/a7240387e8cf3966299948b4594cd42aa4a35c52

Any idea how to modify that test so it fails?

**Comment by lloydmeta** [comment]
@havocp actually upon further investigation, I've found that this is not a problem with Typesafe Config, but a problem with Play. Closing now :) Thanks for your help !

**Comment by skoppar** [comment]
@havocp I am facing exactly same issue with spark and Config. All the details are here:
https://www.mail-archive.com/user@spark.apache.org/msg52766.html

Can you please share your resolution. I have a feeling its the same issue

**Comment by havocp** [comment]
it looks like https://github.com/playframework/playframework/pull/4145 was the play fix from @lloydmeta
