### ISSUE TITLE
Version 1.3.0 published (accidentally?) with Java 8 bytecode

### ISSUE THREAD

**Issue by retronym** [typesafehub/config#322]
```
% curl -L --silent http://search.maven.org/remotecontent?filepath=com/typesafe/config/1.2.0/config-1.2.0.jar > /tmp/config-1.2.0.jar

% javap -v -classpath /tmp/config-1.2.0.jar com/typesafe/config/impl/Tokens | head -n 7
Classfile jar:file:/tmp/config-1.2.0.jar!/com/typesafe/config/impl/Tokens.class
  Last modified 15/01/2014; size 8284 bytes
  MD5 checksum 710bf1482984c85725bc85aaec41e156
  Compiled from "Tokens.java"
final class com.typesafe.config.impl.Tokens
  minor version: 0
  major version: 50

% curl -L --silent http://search.maven.org/remotecontent?filepath=com/typesafe/config/1.3.0/config-1.3.0.jar > /tmp/config-1.3.0.jar

% javap -v -classpath /tmp/config-1.3.0.jar com/typesafe/config/impl/Tokens | head -n 7
Classfile jar:file:/tmp/config-1.3.0.jar!/com/typesafe/config/impl/Tokens.class
  Last modified 08/05/2015; size 9449 bytes
  MD5 checksum 344eb9ac84439400cc9628bc353d6781
  Compiled from "Tokens.java"
final class com.typesafe.config.impl.Tokens
  minor version: 0
  major version: 52
```

Perhaps #244 is related?

**Comment by retronym** [comment]
Oh wait, I see this was intentional. What was the motivation?

The Scala community build is currently failing because of this change.

```
[sbt-twirl-210] [info] Set current project to twirl (in build file:/mnt/dbuild/jenkinsdbuild3/localhome-a8/workspace/Community-2.11.x/target-0.9.1/project-builds/sbt-twirl-210-9fecfd175229ea8243a94e2c7066aac98042f6b7/)
[sbt-twirl-210] java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException$Missing : Unsupported major.minor version 52.0
[sbt-twirl-210] 	at java.lang.ClassLoader.defineClass1(Native Method)
[sbt-twirl-210] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
[sbt-twirl-210] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[sbt-twirl-210] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
[sbt-twirl-210] 	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
[sbt-twirl-210] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
[sbt-twirl-210] 	at java.security.AccessController.doPrivileged(Native Method)
[sbt-twirl-210] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
[sbt-twirl-210] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
[sbt-twirl-210] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
[sbt-twirl-210] 	at com.typesafe.dbuild.DistributedRunner$.rewire(DistributedRunner.scala:694)
[sbt-twirl-210] 	at $df1624be9d4ac0504c8d$$anonfun$$sbtdef$1$$anonfun$apply$1.apply(/mnt/dbuild/jenkinsdbuild3/localhome-a8/workspace/Community-2.11.x/target-0.9.1/project-builds/sbt-twirl-210-9fecfd175229ea8243a94e2c7066aac98042f6b7/ÿÿÿÿÿÿÿÿÿÿ~~~~dbuild~defs.sbt:1)
[sbt-twirl-210] 	at $df1624be9d4ac0504c8d$$anonfun$$sbtdef$1$$anonfun$apply$1.apply(/mnt/dbuild/jenkinsdbuild3/localhome-a8/workspace/Community-2.11.x/target-0.9.1/project-builds/sbt-twirl-210-9fecfd175229ea8243a94e2c7066aac98042f6b7/ÿÿÿÿÿÿÿÿÿÿ~~~~dbuild~defs.sbt:1)
```

**Comment by retronym** [comment]
We've reverted our Java 6 build to an older version of playframework/twirl. We'll make our Java 8 build track Play 2.4.
