### ISSUE TITLE
Improper error messages

### ISSUE THREAD

**Issue by cs0ip** [typesafehub/config#331]
Config version is 1.3.0

```
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_45).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import com.typesafe.config._
import com.typesafe.config._

scala> ConfigFactory.parseString("x = [1, 2, 1.3, 'xxx', {}, null]")
res0: com.typesafe.config.Config = Config(SimpleConfigObject({"x":[1,2,1.3,"'xxx'",{},null]}))

scala> res0.getConfigList("x")
com.typesafe.config.ConfigException$WrongType: String: 1: x has type list of NUMBER rather than list of OBJECT
  at com.typesafe.config.impl.SimpleConfig.getHomogeneousWrappedList(SimpleConfig.java:398)
  at com.typesafe.config.impl.SimpleConfig.getObjectList(SimpleConfig.java:406)
  at com.typesafe.config.impl.SimpleConfig.getConfigList(SimpleConfig.java:411)
  ... 33 elided

scala> res0.getNumberList("x")
com.typesafe.config.ConfigException$WrongType: String: 1: x has type list of STRING rather than list of NUMBER
  at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:333)
  at com.typesafe.config.impl.SimpleConfig.getNumberList(SimpleConfig.java:346)
  ... 33 elided

scala> res0.getStringList("x")
com.typesafe.config.ConfigException$WrongType: String: 1: x has type list of OBJECT rather than list of STRING
  at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:333)
  at com.typesafe.config.impl.SimpleConfig.getStringList(SimpleConfig.java:381)
  ... 33 elided

scala> res0.getObjectList("x")
com.typesafe.config.ConfigException$WrongType: String: 1: x has type list of NUMBER rather than list of OBJECT
  at com.typesafe.config.impl.SimpleConfig.getHomogeneousWrappedList(SimpleConfig.java:398)
  at com.typesafe.config.impl.SimpleConfig.getObjectList(SimpleConfig.java:406)
  ... 33 elided
```

**Comment by havocp** [comment]
I believe it's reporting the type of the first element that can't be converted to what you ask for. (You probably already found `getAnyRefList` if you want a heterogeneous list like this.)

The examples you give work like this:
 * asking for Config: the first element is a number which can't become a Config
 * asking for Number: the first non-numeric element is a String which isn't a valid number
 * asking for String: the numbers can be converted to strings, but the object `{}` cannot so that's the element it fails on
 * asking for Object: same as asking for Config, can't convert numbers to objects

It might be nice to change the error message to be something like "asked for list of OBJECT but element 0 is a NUMBER" since that would be less confusing.

While we're at it I think it'd be nice to lowercase those type names.
