### ISSUE TITLE
`truefoo` does not parse as `Boolean(true)` `UnquotedString(foo)`

### ISSUE THREAD

**Issue by evacchi** [typesafehub/config#345]
According to the informal spec:

> `truefoo` parses as the boolean token `true` followed by the unquoted string `foo`.

However, when trying it inside the REPL:

```scala
scala> import com.typesafe.config.ConfigFactory
import com.typesafe.config.ConfigFactory

scala> val config = ConfigFactory.parseString("term=truefoo")
config: com.typesafe.config.Config = Config(SimpleConfigObject({"term":"truefoo"}))

scala> config.getString("term")
res7: String = truefoo

scala> config.getBoolean("term")
com.typesafe.config.ConfigException$WrongType: String: 1: term has type STRING rather than BOOLEAN
 at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:159)
 at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
 at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
 at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
 at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:214)
 ... 43 elided
```
I would argue that the behaviour of the implementation is actually **more intuitive** than what is described in the spec. 

My proposal is therefore to **adjust the spec** accordingly with the implementation.

**Comment by andreaTP** [comment]
:+1:

**Comment by havocp** [comment]
I think this is just confusing wording. It's probably tokenized as Boolean true then foo, and then concatenated into a string value. I don't remember offhand why the initial tokenization matters. If you read the spec rules about value concatenation maybe it explains a bit more how the final result is a string.

**Comment by havocp** [comment]
unless I'm wrong about this one I think the only action would be some sort of documentation/spec rewording to clarify.
