### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by analytically** [typesafehub/config#355]
```
java.lang.NullPointerException
	at com.typesafe.config.impl.AbstractConfigValue.withFallback(AbstractConfigValue.java:274)
	at com.typesafe.config.impl.AbstractConfigObject.withFallback(AbstractConfigObject.java:139)
	at com.typesafe.config.impl.SimpleConfig.withFallback(SimpleConfig.java:515)
	at com.typesafe.config.impl.SimpleConfig.withFallback(SimpleConfig.java:37)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:212)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:181)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:167)
```

My code:
```
class ServerRouteTest extends FlatSpec with Matchers with ScalatestRouteTest with MockFactory {
  val cfg = ConfigFactory.parseString(
    """
      akka.daemonic = on
    """)

  override protected def createActorSystem(): ActorSystem = ActorSystem("test", ConfigFactory.load(cfg))
}
```

**Comment by havocp** [comment]
Not obvious what could be wrong here. If you look at https://github.com/typesafehub/config/blob/master/config/src/main/java/com/typesafe/config/impl/AbstractConfigValue.java#L274 the only thing that would be null to cause this is `mergeable`, and `parseString` should never return null. So, checking assumptions...

 * you could assert `cfg != null` before you do the `ConfigFactory.load`
 * you could get a longer stack trace to be sure the `ConfigFactory.load` in the trace is the one in your code snippet, rather than one inside Akka somewhere
 * let me know the version you're using, let's be sure it matches the latest source I linked to above
 * a test case without akka involved would be useful since we could put it in the config test suite

Thanks for the report!

**Comment by analytically** [comment]
Hmm indeed, cfg is null here. OK closing.

**Comment by havocp** [comment]
Cool. Probably an order-of-initialization problem, createActorSystem is called before cfg is initialized.
