### ISSUE TITLE
Error resolving configuration substitution

### ISSUE THREAD

**Issue by jasonf20** [typesafehub/config#378]
In some situations there seems to be a bug which causes the following error (even thought as far as I can tell it should be able to resolve the value): 
```
Exception in thread "main" com.typesafe.config.ConfigException$UnresolvedSubstitution: conf/sub-conf.conf @ ...: Could not resolve substitution to a value: ${integ.config1.a.value} was part of a cycle of substitutions involving ${integ.config1.a.value}, ${integ.config1.a.value}
```

I have created a sample project which recreates this issue:
https://github.com/jasonf20/typesafe-config-bug

I have had this happen a few times and have resorted to manually replacing the values in my code. However it would be nice if this would work :)

**Comment by havocp** [comment]
is the include of a sub-conf needed to trigger it, or does it also happen if you put the contents of the include directly in the main file?

Usually false cycles are because we get over-eager and resolve a field that doesn't need to be resolved yet. To debug this essentially what I'd do is make the simplest unit test case I could, and then get the stack trace of that exception and try to figure out why config1.b.value is re-visited while trying to get the value of `${config1.a.value}`. Perhaps some part of the code tries to resolve the entire `config1` object for some reason, maybe in order to merge it with `${default}`, I don't know. But in theory I don't think the object needs to be resolved in order to merge it.

**Comment by jasonf20** [comment]
Yea I don't think it needs to be resolved. I think the bug might be something like when doing `integ = ${default} {...config...}` then It tries to resolve the ` {...config...}` part with `allowUnresolved =  false` or something along those lines.

I checked and the bug seems to happen also without the include like so:
```conf
default {
}

integ = ${default} {
  config1 {
    a {
      value = 1
    }

    b {
      value = ${config1.a.value}
    }
  }
}
```
and also where `b.value = ${integ.config1.a.value}` 

The include however is relevant however because it makes it allows you to use `${config1.a.value}` and not `${integ.config1.a.value}` since you don't know where it will be included from.

**Comment by clehene** [comment]
@havocp here's a unit test showing the bug https://github.com/tapwater/config/commit/a82cb3216ad2c2d3260b2df93ca24f152999007c

**Comment by clehene** [comment]
Here's the stacktrace
```
[error] Test com.typesafe.config.impl.ConfigSubstitutionTest.incorrectCycleFailure failed: com.typesafe.config.ConfigException$UnresolvedSubstitution: test string: 7: Could not resolve substitution to a value: ${override.a} was part of a cycle of substitutions involving ${override.a}, ${override.a}, took 0.001 sec
[error]     at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:104)
[error]     at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
[error]     at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
[error]     at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:380)
[error]     at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:313)
[error]     at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:399)
[error]     at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
[error]     at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
[error]     at com.typesafe.config.impl.ConfigConcatenation.resolveSubstitutions(ConfigConcatenation.java:205)
[error]     at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
[error]     at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
[error]     at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:380)
[error]     at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:313)
[error]     at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:399)
[error]     at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
[error]     at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
[error]     at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:231)
[error]     at com.typesafe.config.impl.ConfigSubstitutionTest.resolve(ConfigSubstitutionTest.scala:28)
[error]     at com.typesafe.config.impl.ConfigSubstitutionTest.incorrectCycleFailure(ConfigSubstitutionTest.scala:1292)
[error]     ...
[error] Caused by: com.typesafe.config.impl.AbstractConfigValue$NotPossibleToResolve: was not possible to resolve
[error]     at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:176)
[error]     at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
[error]     at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:380)
[error]     at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:313)
[error]     at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:399)
[error]     at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
[error]     at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
[error]     at com.typesafe.config.impl.ConfigConcatenation.resolveSubstitutions(ConfigConcatenation.java:205)
[error]     at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
[error]     at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
[error]     at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:366)
[error]     at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:313)
[error]     at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:399)
[error]     at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
[error]     at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
[error]     at com.typesafe.config.impl.ResolveSource.findInObject(ResolveSource.java:47)
[error]     at com.typesafe.config.impl.ResolveSource.lookupSubst(ResolveSource.java:97)
[error]     at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:74)
[error]     ... 51 more
```

**Comment by havocp** [comment]
If you’re investigating here you might also look at the -Dconfig.trace=substitutions output (while running only the one unit test ... the output for the entire test suite will be hard to unpack).

This code is a little brain-melty though, be warned. There’s a lot of discussion of how it works in HOCON.md and a fair number of existing tests.

**Comment by mohsenpx** [comment]
@havocp 
I have same problem in Ubuntu.
using the ```-Dconfig.trace=substitutions ``` , I receive this output:
`An exception or error caused a run to abort: Configuration error[resolve getting too deep] 
Configuration error: Configuration error[resolve getting too deep]
`
