### ISSUE TITLE
UUID key can't be parsed correctly

### ISSUE THREAD

**Issue by venusgun** [typesafehub/config#480]
Hi,

When I have a config with UUID key:
```
config = {
    "92806961-7548-48f0-943c-8fb861bb642f" : 1.0
}
```

And try to read the double value:
```
Double value = play.Configuration.root().getConfig("config").getDouble("92806961-7548-48f0-943c-8fb861bb642f");
```

It seems to try to parse the key as a number, how do I solve this?
```
com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path '92806961-7548-48f0-943c-8fb861bb642f': Token not allowed in path expression: '92806961-7548-48' (Invalid number: '92806961-7548-48') (you can double-quote this token if you really want it here)
	at com.typesafe.config.impl.Parser.parsePathExpression(Parser.java:934) ~[com.typesafe.config-1.0.2.jar:na]
	at com.typesafe.config.impl.Parser.parsePath(Parser.java:974) ~[com.typesafe.config-1.0.2.jar:na]
	at com.typesafe.config.impl.Path.newPath(Path.java:220) ~[com.typesafe.config-1.0.2.jar:na]
	at com.typesafe.config.impl.SimpleConfig.hasPath(SimpleConfig.java:71) ~[com.typesafe.config-1.0.2.jar:na]
	at play.api.Configuration.reportError(Configuration.scala:570) ~[com.typesafe.play.play_2.10-2.2.3.jar:2.2.3]
	at play.api.Configuration.readValue(Configuration.scala:128) ~[com.typesafe.play.play_2.10-2.2.3.jar:2.2.3]
	at play.api.Configuration.getDouble(Configuration.scala:270) ~[com.typesafe.play.play_2.10-2.2.3.jar:2.2.3]
	at play.Configuration.getDouble(Configuration.java:164) ~[com.typesafe.play.play_2.10-2.2.3.jar:2.2.3]
```

Thank you.

**Comment by ryantheleach** [comment]
A UUID is not a double?

**Comment by havocp** [comment]
Paths that look like numbers may need to be quoted. But I kind of thought we'd fixed that ...

**Comment by venusgun** [comment]
I don't think the numbers need to be quoted, I have other cases working when the UUID key doesn't look like a  number.

Can you confirm which version was this issue fixed? Thanks.

**Comment by havocp** [comment]
The commit I'm thinking of is https://github.com/typesafehub/config/commit/7ac81ecb5eed88a458e5d2b9d6da53eaba73e1de  which would be in 1.2.0 and above.
